In [8]:
#Creating an array and adding two Matrices using List
Matrix1=[[1,2,3],[4,5,6]]
Matrix2=[[7,8,9],[10,11,12]]
#Intializing a result matrix
result=[[0,0,0],[0,0,0]]
#Performing Matrix addition
for i in range(len(Matrix1)):
    for j in range(len(Matrix1[0])):
        result[i][j]=Matrix1[i][j]+Matrix2[i][j]
#Displaying the result
print("Matrix 1:")
for row in Matrix1:
    print(row)
print("\nMatrix 2:")
for row in Matrix2:
    print(row)
print("\nSum of Matrix 1 and Matrix 2 is:")
for row in result:
    print(row)

Matrix 1:
[1, 2, 3]
[4, 5, 6]

Matrix 2:
[7, 8, 9]
[10, 11, 12]

Sum of Matrix 1 and Matrix 2 is:
[8, 10, 12]
[14, 16, 18]


In [10]:
#Creating an array and adding two Matrices using NumPy
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("Matrix 1:\n",a)
b=np.array([[7,8,9],[10,11,12]])
print("\nMatrix 2:\n",b)
result=a+b
print("\nSum of Matrix 1 and Matrix 2 is:\n",result)

Matrix 1:
 [[1 2 3]
 [4 5 6]]

Matrix 2:
 [[ 7  8  9]
 [10 11 12]]

Sum of Matrix 1 and Matrix 2 is:
 [[ 8 10 12]
 [14 16 18]]
